---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: infadomain-storage-class
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  resourceGroup: FCSA_Informatica
  shareName: infadomain-storage-class
  skuName: Standard_LRS
  storageAccount: fcsainformaticastorage
provisioner: kubernetes.io/azure-file
