---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infadomain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Informatica
      domain: informatica
      purpose: infa-master
  serviceName: informatica
  template:
    metadata:
      labels:
        app: Informatica
        domain: informatica
        purpose: infa-master
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: purpose
                      operator: In
                      values:
                        - infa-master
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - /Installer/kubernetes_laucher.sh
          command:
            - sh
          env:
            - name: INFA_ENV_TYPE
              value: Kubernetes
            - name: INFA_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INFA_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFA_MASTER_POD_NAME
              value: infadomain-0
          image: informatica1052:1.0
          imagePullPolicy: Always
          name: infadomain
          ports:
            - containerPort: 8075
          resources:
            limits:
              cpu: 4000m
              memory: 16Gi
            requests:
              cpu: 2000m
              memory: 12Gi
          volumeMounts:
            - mountPath: /home/Informatica/K8sSharedVolume
              name: persistent-volume
            - mountPath: /home/Informatica/K8sVolume
              name: persistent-pod-volume
            - mountPath: /home/Informatica/K8sConfigMap
              name: config-map-volume
      hostname: infadomain
      imagePullSecrets:
        - name: registry-cred
      subdomain: informatica
      terminationGracePeriodSeconds: 300
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: infadomain-shared-volume
        - configMap:
            items:
              - key: SilentInput.properties
                path: SilentInput.properties
              - key: license.key
                path: license.key
            name: infadomain-config-map
          name: config-map-volume
  volumeClaimTemplates:
    - metadata:
        name: persistent-pod-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
