---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infadomain-shared-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: infadomain-storage-class
