
name: 'Terraform-aks'
on:
  push:
    branches:
      - main
    paths:
      - '**/actions/Terraform-aks/**'
  pull_request:
#  workflow_dispatch: #this attribute will enable the manual run to the pipeline
  
jobs:
  terraform:
    name: "Terraform"
    #terraform_plan:
   # name: 'Terraform'
    #environment: production
    env: 
      #ROOT_PATH: '../Terrafrom-aks/'
      #ROOT_PATH: '../'
      #ROOT_PATH:  'git::https://github.com/FcscEDN/Tfm_Azur_Infa10.5/tree/main/Terrafrom-aks'
      VAR_AP_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      VAR_AP_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      VAR_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      VAR_AP_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    #defaults:
     # run:
      #  shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5   

      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -lock-timeout=600s
        continue-on-error: true
 
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -lock-timeout=7200s
        
    # - name: terraform
 #      uses: robertdebock/terraform-action@1.1.2
 #      with:
  #        action: init
 #         directory: ${{env.ROOT_PATH}}
#     - name: terraform validate
 #      uses: robertdebock/terraform-action@1.1.2
  #     with:
   #       action: validate
    #      directory: ${{env.ROOT_PATH}}
    
     #- name: terraform plan
     #  uses: robertdebock/terraform-action@1.1.2
      # with:
       #   action: plan
       #   directory: ${{env.ROOT_PATH}}

#     - name: terraform apply
 #      uses: robertdebock/terraform-action@1.1.2
  #     with:
   #       action: plan
    #      directory: ${{env.ROOT_PATH}}
          
