on: [push]

name: T-Az

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}} 

      - name: Checkout source code
        uses: actions/checkout@v2

